### ISSUE TITLE
More Circles

### ISSUE THREAD

**Issue by Jadowo** [Devil4ngle/squadmortar#2]
Any chance to add more circle at like 100 mil increments?

**Comment by Devil4ngle** [comment]
@Jadowo  Can you expand on what you mean with "more circle"?

**Comment by Jadowo** [comment]
> @Jadowo  Can you expand on what you mean with "more circle"?

So right now when you select mortars there is a wide circle that roughly shows max range. Is it possible to change the circle to show the actual max range? If this is possible it would be cool to have it also show lines for ranges in increments. It won't be a circle anymore but a weird squiggly line since elevation changes. But if it's not possible is it possible to have a setting where the targets are locked to the mortar itself?

**Comment by Jadowo** [comment]
![image](https://github.com/Devil4ngle/squadmortar/assets/33840143/5ec4e2e3-c57a-450d-8858-dd2c83f23b6e)
Something like this?

**Comment by Devil4ngle** [comment]
Feature was added
