### ISSUE TITLE
contour range lines

### ISSUE THREAD

**Issue by itsdarf** [Devil4ngle/squadmortar#3]
Hello! I saw the update for the max ranges! It was great! The other guy also requested more ranges in between I think it looks something like adjustable contour lines would be great!

**Comment by Devil4ngle** [comment]
hello @itsdarf , can you expand on what the function of more ranges in between would be? Thanks for the feedback

**Comment by Jadowo** [comment]
I had asked something similar in the other thread. Having more the lines of ranges in between would allow for quicker target accquisition. Lets say I'm targeting Building A at 300 degree and 1200 mils and my next target Building B is at 120 degrees and also at 1200 mils I could get that information quickly just by following the line I'm on. If the target was closer or futher by lets say 100 meters I could see that the target isn't on the line and probably closer to a different line lets say 1300 mils entirely letting me quickly adjust and estimate without having to select a target. It's kind of similar to what squadmortar XYZ had for it's grid for a dispersion of mortars in an area but over a larger area.

**Comment by Devil4ngle** [comment]
website is now handled by https://github.com/sh4rkman/SquadCalc
